version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "npm"
    directory: "/tests/e2e"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "tests"

  - package-ecosystem: "npm"
    directory: "/tests/app"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "tests"
