#!/bin/bash
# generate-changelog.sh — Auto-generate release changelog from git history
#
# Compares source-pins.json between two releases (or current build vs previous
# release tag) and generates a Markdown changelog grouped by type.
#
# Usage:
#   ./scripts/generate-changelog.sh [options]
#
#   --from TAG|PINS       Previous release tag (e.g. v16.2) or source-pins.json path
#   --to TAG|PINS         Current release tag or source-pins.json path (default: current build)
#   --output FILE         Output file (default: CHANGELOG-<build-id>.md)
#   --build-dir PATH      Build output dir (default: ga_output)
#   --repos-dir PATH      Parent dir containing all repo checkouts (default: /home/user/git)
#
# If --from is not given, uses the most recent git tag on ha-operating-system.
#
# Output format:
#   # Release v16.3 (2026-03-31)
#   ## ha-operating-system
#   ### Features
#   - feat: QR code PIN auto-injection (#abc1234)
#   ### Fixes
#   - fix: FULL_DISK_SIZE 9216M for 8GB data partition (#def5678)

set -euo pipefail

BUILD_DIR="${BUILD_DIR:-ga_output}"
REPOS_DIR="${REPOS_DIR:-/home/user/git}"
FROM_REF=""
TO_REF=""
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --from)      FROM_REF="$2"; shift 2 ;;
    --to)        TO_REF="$2"; shift 2 ;;
    --output)    OUTPUT="$2"; shift 2 ;;
    --build-dir) BUILD_DIR="$2"; shift 2 ;;
    --repos-dir) REPOS_DIR="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# --- Resolve current build pins ---
CURRENT_PINS="${BUILD_DIR}/images/configs/source-pins.json"
if [[ -n "$TO_REF" ]] && [[ -f "$TO_REF" ]]; then
  CURRENT_PINS="$TO_REF"
fi
if [[ ! -f "$CURRENT_PINS" ]]; then
  echo "ERROR: Current source-pins.json not found: $CURRENT_PINS" >&2
  exit 1
fi

BUILD_ID="$(jq -r '.build_id // "unknown"' "$CURRENT_PINS" 2>/dev/null)"
BUILD_DATE="$(jq -r '.build_date // "'$(date '+%Y-%m-%d')'"' "$CURRENT_PINS" 2>/dev/null)"
[[ -z "$OUTPUT" ]] && OUTPUT="CHANGELOG-${BUILD_ID}.md"

# --- Resolve previous release ---
# Map repo names to local paths
declare -A REPO_MAP=(
  ["ha-operating-system"]="${REPOS_DIR}/ha-operating-system"
  ["homeassistant_frontend"]="${REPOS_DIR}/homeassistant_frontend"
  ["homeassisant_core"]="${REPOS_DIR}/homeassisant_core"
  ["ha-supervisor"]="${REPOS_DIR}/ha-supervisor"
  ["haos-version"]="${REPOS_DIR}/haos-version"
  ["ga-flasher-py"]="${REPOS_DIR}/ga-flasher-py"
  ["USB-Dongle-OpenStick"]="${REPOS_DIR}/USB-Dongle-OpenStick"
)

# Map repo dirs to display names
declare -A REPO_DISPLAY=(
  ["ha-operating-system"]="ha-operating-system"
  ["homeassistant_frontend"]="frontend"
  ["homeassisant_core"]="ha-core"
  ["ha-supervisor"]="ha-supervisor"
  ["haos-version"]="haos-version"
  ["ga-flasher-py"]="ga-flasher-py"
  ["USB-Dongle-OpenStick"]="USB-Dongle-OpenStick"
)

# If --from is a tag, get the previous build's source-pins
PREV_PINS=""
if [[ -n "$FROM_REF" ]] && [[ -f "$FROM_REF" ]]; then
  PREV_PINS="$FROM_REF"
elif [[ -n "$FROM_REF" ]]; then
  # Try to find source-pins.json from a release archive or git tag
  echo "WARN: --from tag lookup not yet implemented, will use git log with date range" >&2
fi

# --- Helper: get SHA for a repo from pins JSON ---
get_pin_sha() {
  local pins_file="$1" repo_name="$2"
  jq -r --arg name "$repo_name" '
    .repositories[]? | select(.name == $name or .url | contains($name)) | .sha // empty
  ' "$pins_file" 2>/dev/null || true
}

# --- Helper: categorize commit by conventional commit prefix ---
categorize() {
  local msg="$1"
  case "$msg" in
    feat:*|feat\(*) echo "Features" ;;
    fix:*|fix\(*)   echo "Fixes" ;;
    docs:*|docs\(*) echo "Documentation" ;;
    test:*|test\(*) echo "Tests" ;;
    refactor:*|refactor\(*) echo "Refactoring" ;;
    perf:*|perf\(*) echo "Performance" ;;
    ci:*|ci\(*)     echo "CI" ;;
    *)              echo "Other" ;;
  esac
}

# --- Generate changelog ---
{
  echo "# Release ${BUILD_ID} (${BUILD_DATE})"
  echo ""
  echo "> Auto-generated by \`generate-changelog.sh\`"
  echo ""

  # Build summary from current pins
  FE_VER="$(jq -r '.ha_core_frontend.pyversion // "unknown"' "$CURRENT_PINS" 2>/dev/null)"
  FE_SHA="$(jq -r '.ha_core_frontend.sha // "unknown"' "$CURRENT_PINS" 2>/dev/null)"
  NB_VER="$(jq -r '.standalone_tools.netbird.version // "unknown"' "$CURRENT_PINS" 2>/dev/null)"

  echo "## Build Info"
  echo ""
  echo "| Component | Version |"
  echo "|-----------|---------|"
  echo "| Build ID | \`${BUILD_ID}\` |"
  echo "| Frontend | \`${FE_VER}\` (\`${FE_SHA:0:7}\`) |"
  echo "| NetBird | \`${NB_VER}\` |"
  echo ""

  FOUND_CHANGES=false

  for repo_key in "${!REPO_MAP[@]}"; do
    repo_dir="${REPO_MAP[$repo_key]}"
    display="${REPO_DISPLAY[$repo_key]}"

    [[ -d "$repo_dir/.git" ]] || continue

    # Determine commit range
    if [[ -n "$PREV_PINS" ]]; then
      old_sha="$(get_pin_sha "$PREV_PINS" "$repo_key")"
      new_sha="$(get_pin_sha "$CURRENT_PINS" "$repo_key")"
      [[ -z "$old_sha" || -z "$new_sha" || "$old_sha" == "$new_sha" ]] && continue
      range="${old_sha}..${new_sha}"
    elif [[ -n "$FROM_REF" ]]; then
      # Use tag or date-based range
      range="${FROM_REF}..HEAD"
    else
      # Default: last 50 commits or since last tag
      last_tag="$(git -C "$repo_dir" describe --tags --abbrev=0 2>/dev/null || true)"
      if [[ -n "$last_tag" ]]; then
        range="${last_tag}..HEAD"
      else
        range="--max-count=50"
      fi
    fi

    # Get commits
    commits="$(git -C "$repo_dir" log $range --oneline --format="%h %s" --no-merges 2>/dev/null || true)"
    [[ -z "$commits" ]] && continue

    FOUND_CHANGES=true
    echo "## ${display}"
    echo ""

    # Group by category
    declare -A CATEGORIES
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      sha="${line%% *}"
      msg="${line#* }"
      # Skip Co-Authored-By and merge commits
      [[ "$msg" == Co-Authored-By* ]] && continue
      [[ "$msg" == Merge* ]] && continue
      cat="$(categorize "$msg")"
      CATEGORIES["$cat"]="${CATEGORIES[$cat]:-}
- ${msg} (\`${sha}\`)"
    done <<< "$commits"

    # Print categories in order
    for cat in "Features" "Fixes" "Tests" "Documentation" "Performance" "Refactoring" "CI" "Other"; do
      if [[ -n "${CATEGORIES[$cat]:-}" ]]; then
        echo "### ${cat}"
        echo "${CATEGORIES[$cat]}"
        echo ""
      fi
    done

    unset CATEGORIES
    declare -A CATEGORIES
  done

  if ! $FOUND_CHANGES; then
    echo "*No changes detected (no previous release to compare against)*"
    echo ""
    echo "To compare against a previous release:"
    echo "\`\`\`"
    echo "./scripts/generate-changelog.sh --from path/to/old/source-pins.json"
    echo "\`\`\`"
  fi

  echo "---"
  echo "*Generated $(date '+%Y-%m-%d %H:%M:%S') by \`scripts/generate-changelog.sh\`*"

} > "$OUTPUT"

echo "Changelog generated: $OUTPUT"
wc -l "$OUTPUT" | awk '{print "  Lines:", $1}'
